version: 1
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    formatter: default
    filename: logs/freight_api.log
    level: DEBUG

  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG

loggers:
  uvicorn.error:
    level: DEBUG
    handlers: [file, console]
    propagate: no

  uvicorn.access:
    level: DEBUG
    handlers: [file, console]
    propagate: no
